
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hioribtoyuxrrxmcmldi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhpb3JpYnRveXV4cnJ4bWNtbGRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNzQwODAsImV4cCI6MjA1ODc1MDA4MH0.oO3Kqc2CbEqIKu4yzrH9YWNGrEipjwS8nCflNxX2YCU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
      storage: localStorage,
    },
    global: {
      headers: {
        'Accept-Profile': 'public',
      },
    },
    db: {
      schema: 'public',
    },
  }
);

// Add error handling for database schema issues with improved logging
const checkConnection = async () => {
  try {
    // Try a simple query to validate connection
    const { data, error } = await supabase.from('profiles').select('id').limit(1);
    
    if (error) {
      if (error.code === 'PGRST106' || error.message.includes('schema must be one of the following')) {
        console.error('Database schema error detected:', error.message);
        // Store a flag in session storage indicating schema issue
        sessionStorage.setItem('db_schema_error', 'true');
      } else {
        console.error('Database connection error:', error.message);
      }
      return false;
    } else {
      // Clear any previous schema error flag if connection is successful
      console.log('Database connection successful, clearing schema error flag');
      sessionStorage.removeItem('db_schema_error');
      return true;
    }
  } catch (err) {
    console.error('Error checking database connection:', err);
    return false;
  }
};

// Check connection on initial load
checkConnection();

// Configure the redirect URL for authentication
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'SIGNED_IN' || event === 'TOKEN_REFRESHED') {
    // Set redirect URL for the current origin
    const redirectTo = `${window.location.origin}/verify-email`;
    console.log("Setting redirect URL to:", redirectTo);
    
    // Check connection again after sign in
    checkConnection();
  }
});

// Get the current domain for email settings
const currentDomain = window.location.origin;
console.log("Current application domain:", currentDomain);
